/* Copyright (c) 2017 ABI Cube */
/* Shabnam Watson */
/* Sample code for reading data from SSAS DMVs using a Linked Server. */
/* SSAS_TAB is the name of a SSAS Linked Server. */
/* Here are some useful SSAS DMVs:
	$SYSTEM.DISCOVER_TRACES
	$SYSTEM.DISCOVER_OBJECT_MEMORY_USAGE
	$SYSTEM.DISCOVER_OBJECT_ACTIVITY
	$SYSTEM.DISCOVER_SESSIONS
	Full list of SSAS DMVs:
		https://docs.microsoft.com/en-us/sql/analysis-services/instances/use-dynamic-management-views-dmvs-to-monitor-analysis-services
*/

SELECT       SESSION_SPID,
			 SESSION_CONNECTION_ID,
			 CAST(SESSION_USER_NAME AS NVARCHAR(255)) AS SESSION_USER_NAME,
			 CAST(SESSION_CURRENT_DATABASE AS NVARCHAR(255)) AS SESSION_CURRENT_DATABASE,
			 SESSION_USED_MEMORY AS [USED MEMORY],
			 SESSION_START_TIME, 
             SESSION_ELAPSED_TIME_MS,
			 SESSION_LAST_COMMAND_START_TIME,
			 SESSION_LAST_COMMAND_END_TIME,
			 SESSION_LAST_COMMAND_ELAPSED_TIME_MS,
			 SESSION_IDLE_TIME_MS,
			 SESSION_CPU_TIME_MS, 
             CAST(SESSION_LAST_COMMAND AS NVARCHAR(4000)) AS SESSION_LAST_COMMAND,
			 SESSION_LAST_COMMAND_CPU_TIME_MS,
			 CASE	SESSION_STATUS
				WHEN 0 THEN 'Idle'
				WHEN 1 THEN 'Active'
				WHEN 2 THEN 'Blocked'
				WHEN 3 THEN 'Cancelled' 
			 END	AS SESSION_STATUS,
			 SESSION_READS,
			 SESSION_WRITES,
			 SESSION_READ_KB,
			 SESSION_WRITE_KB,
			 SESSION_COMMAND_COUNT,             
			 CAST(THREAD_POOL_USED AS NVARCHAR(255)) AS THREAD_POOL_USED
			 
FROM         OPENQUERY(SSAS_TAB, 'SELECT * FROM $SYSTEM.DISCOVER_SESSIONS 
								  WHERE SESSION_USER_NAME <>''ABI1\PBI_User''') AS Disc_Sessions 