/* Copyright (c) 2018 ABI Cube */
/* Shabnam Watson */
/* Sample code that shows how you can use 
   sys.fn_xe_file_target_read_file to read an XEL file which is the output file type
   generated by Extended Events traces.
*/

SELECT        CAST(event_data AS XML) AS XE
FROM          sys.fn_xe_file_target_read_file('C:\Extended Events Log Files\TABULAR\test*.xel', NULL, NULL, NULL)
